version: "3"

services:
  app:
    container_name: nadache-inache
    build:
      context: ./
      dockerfile: Dockerfile

    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - external

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true